'use strict';
// One-off actions: cleanups and repairs. They aren't toggles, so there's nothing to "revert" —
// the confirmation dialog says so plainly where it matters (e.g. emptying the Recycle Bin).
const ALL = ['win32', 'darwin', 'linux', 'chromeos'];
const A = (o) => ({ kind: 'action', risk: 'safe', admin: false, ...o });

// Shell helper for macOS/Linux cleanups: deletes files older than N minutes inside fixed folders we define
// (never user input), removes empty sub-folders, and prints how much space was freed.
const SH_CLEAR = `woof_freed=0
woof_clear() {
  d="$1"; [ -n "$d" ] && [ -d "$d" ] || return 0
  b=$(du -sk "$d" 2>/dev/null | cut -f1)
  find "$d" -mindepth 1 -type f -mmin +"$2" -delete 2>/dev/null
  find "$d" -mindepth 1 -type d -empty -delete 2>/dev/null
  a=$(du -sk "$d" 2>/dev/null | cut -f1)
  woof_freed=$(( woof_freed + \${b:-0} - \${a:-0} ))
}
`;
const shClear = (dirs, minutes) => `${SH_CLEAR}${dirs.map((d) => `woof_clear ${d} ${minutes}`).join('\n')}
echo "WOOF_RESULT {\\"freed\\": $(( woof_freed * 1024 ))}"
`;

// Preinstalled Windows apps we offer to remove (current user only, reinstallable from the Microsoft Store).
const BLOAT = [
  ['Microsoft.BingNews', 'News'], ['Microsoft.BingWeather', 'Weather'], ['Microsoft.GetHelp', 'Get Help'], ['Microsoft.Getstarted', 'Tips'],
  ['Microsoft.MicrosoftSolitaireCollection', 'Solitaire Collection'], ['Microsoft.People', 'People'], ['Microsoft.WindowsFeedbackHub', 'Feedback Hub'],
  ['Microsoft.WindowsMaps', 'Maps'], ['Microsoft.MixedReality.Portal', 'Mixed Reality Portal'], ['Microsoft.MicrosoftOfficeHub', 'Microsoft 365 (Office) hub'],
  ['Microsoft.Todos', 'Microsoft To Do'], ['Microsoft.PowerAutomateDesktop', 'Power Automate'], ['Clipchamp.Clipchamp', 'Clipchamp'],
  ['Microsoft.549981C3F5F10', 'Cortana app'], ['Microsoft.ZuneVideo', 'Films & TV'], ['Microsoft.SkypeApp', 'Skype'], ['Microsoft.3DBuilder', '3D Builder'],
  ['Microsoft.Microsoft3DViewer', '3D Viewer'], ['MicrosoftCorporationII.MicrosoftFamily', 'Family Safety'], ['Microsoft.BingSearch', 'Bing Search'],
];

module.exports = [
  A({ id: 'act-restore-point', kind: 'restorePoint', name: 'Create a restore point', category: 'repair', os: ['win32'], admin: true, desc: 'A Windows System Restore point you can roll back to from Windows itself.', long: { what: 'Creates a System Restore point (and turns System Protection on for your Windows drive if it was off).', why: 'A second safety net on top of Woof Tweaks\' own backups.', risk: 'Windows allows one restore point per 24 hours.' } }),
  A({ id: 'act-flush-dns', name: 'Flush DNS cache', category: 'network', os: ['win32', 'darwin', 'linux'], admin: process.platform !== 'win32', desc: 'Fixes "can\'t connect" after a server/IP change.', long: { what: 'Clears the cached DNS lookups.', why: 'Stale entries can send launchers to old servers.', risk: 'Safe.' }, win: { kind: 'flushDns' }, sh: process.platform === 'darwin' ? 'dscacheutil -flushcache; killall -HUP mDNSResponder' : '(resolvectl flush-caches 2>/dev/null || systemd-resolve --flush-caches 2>/dev/null || true)' }),
  A({ id: 'act-network-reset', name: 'Reset Winsock and TCP/IP', category: 'network', os: ['win32'], admin: true, risk: 'moderate', reboot: 'restart', confirm: 'This resets Windows networking to defaults (VPN adapters may need reinstalling) and needs a restart.', desc: 'Fixes broken internet after VPNs, malware or bad tweak tools.', long: { what: 'Runs "netsh winsock reset" and "netsh int ip reset".', why: 'Repairs a corrupted network stack.', risk: 'Some VPN/proxy software may need reinstalling. Restart required.' }, win: { kind: 'networkReset' } }),
  A({ id: 'act-clear-temp', name: 'Clear temporary files', category: 'cleanup', os: ALL, desc: 'Deletes temp files older than a day.', long: { what: 'Deletes files older than 24 hours from your temp folder. Files in use are skipped.', why: 'Frees disk space; some games misbehave when the temp folder is huge.', risk: 'Safe.' }, win: { kind: 'clearFolders', paths: ['%TEMP%'], olderThanHours: 24 }, sh: shClear(process.platform === 'darwin' ? ['"$(getconf DARWIN_USER_TEMP_DIR)"'] : ['"$HOME/.cache/thumbnails"'], 1440) }),
  A({ id: 'act-clear-shaders', name: 'Clear GPU shader caches', category: 'cleanup', os: ['win32', 'darwin', 'linux'], confirm: 'Close your games first. The first launch afterwards rebuilds shaders, so expect a little stutter for a few minutes.', desc: 'Fixes stutter/crashes caused by corrupt shader caches (DirectX, NVIDIA, AMD, Intel, Mesa, Metal).', long: { what: 'Deletes the DirectX, NVIDIA, AMD and Intel shader caches (Windows), the Metal cache (macOS) or Mesa/NVIDIA caches (Linux).', why: 'Corrupt or outdated caches (often after a driver update) cause stutter and crashes.', risk: 'Games rebuild shaders on next launch.' }, win: { kind: 'clearFolders', olderThanHours: 0, paths: ['%LOCALAPPDATA%\\D3DSCache', '%LOCALAPPDATA%\\NVIDIA\\DXCache', '%LOCALAPPDATA%\\NVIDIA\\GLCache', '%USERPROFILE%\\AppData\\LocalLow\\NVIDIA\\PerDriverVersion\\DXCache', '%LOCALAPPDATA%\\AMD\\DxCache', '%LOCALAPPDATA%\\AMD\\DxcCache', '%LOCALAPPDATA%\\AMD\\VkCache', '%LOCALAPPDATA%\\Intel\\ShaderCache'] }, sh: shClear(process.platform === 'darwin' ? ['"$(getconf DARWIN_USER_CACHE_DIR)com.apple.metal"'] : ['"$HOME/.cache/mesa_shader_cache"', '"$HOME/.cache/mesa_shader_cache_db"', '"$HOME/.cache/nvidia/GLCache"', '"$HOME/.nv/GLCache"'], 0) }),
  A({ id: 'act-clear-crash-dumps', name: 'Clear crash dumps and old logs', category: 'cleanup', os: ['win32', 'darwin'], desc: 'Deletes old crash dumps and diagnostic reports.', long: { what: 'Windows: your CrashDumps folder. macOS: diagnostic reports and logs older than 7 days.', why: 'Can free several GB after repeated game crashes.', risk: 'Safe — but if you\'re sending a crash report to a game\'s support, do that first.' }, win: { kind: 'clearFolders', paths: ['%LOCALAPPDATA%\\CrashDumps'], olderThanHours: 0 }, sh: shClear(['"$HOME/Library/Logs/DiagnosticReports"', '"$HOME/Library/Logs"'], 10080) }),
  A({ id: 'act-clear-update-cache', name: 'Clear Windows Update download cache', category: 'cleanup', os: ['win32'], admin: true, desc: 'Fixes stuck updates and frees space.', long: { what: 'Stops Windows Update briefly and empties SoftwareDistribution\\Download.', why: 'Corrupt downloads make updates fail repeatedly and waste GBs.', risk: 'Windows re-downloads any pending update.' }, win: { kind: 'clearUpdateCache' } }),
  A({ id: 'act-empty-bin', name: 'Empty the Recycle Bin / Trash', category: 'cleanup', os: ['win32', 'darwin', 'linux'], risk: 'moderate', confirm: 'Files in the Recycle Bin/Trash will be permanently deleted. This can\'t be undone.', desc: 'Permanently deletes what\'s in the bin.', long: { what: 'Empties the Recycle Bin (Windows) or Trash (macOS/Linux).', why: 'Frees disk space.', risk: 'Permanent — Woof Tweaks can\'t bring the files back.' }, win: { kind: 'recycleBin' }, sh: process.platform === 'darwin' ? 'find "$HOME/.Trash" -mindepth 1 -maxdepth 1 -exec rm -rf {} + 2>/dev/null; echo done' : 'rm -rf "$HOME/.local/share/Trash/files/"* "$HOME/.local/share/Trash/info/"* 2>/dev/null; echo done' }),
  A({ id: 'act-trim', name: 'Run SSD TRIM now', category: 'repair', os: ['win32', 'linux'], admin: true, desc: 'Tells your SSD which blocks are free, keeping writes fast.', long: { what: 'Windows: Optimize-Volume -ReTrim on your Windows drive. Linux: fstrim on all mounted filesystems.', why: 'Keeps SSD write speed up. Windows also does this weekly on its own — we never turn that schedule off.', risk: 'Safe.' }, win: { kind: 'retrim' }, sh: 'fstrim -av' }),
  A({ id: 'act-sfc', name: 'Check & repair system files (SFC)', category: 'repair', os: ['win32'], admin: true, timeout: 90 * 60_000, progress: 'Checking system files — this can take 10–20 minutes…', desc: 'Repairs corrupted Windows files that cause crashes.', long: { what: 'Runs "sfc /scannow".', why: 'Corrupt system files cause random crashes and errors.', risk: 'Safe. Takes 10–20 minutes.' }, win: { kind: 'sfc' } }),
  A({ id: 'act-dism', name: 'Repair the Windows image (DISM)', category: 'repair', os: ['win32'], admin: true, timeout: 120 * 60_000, progress: 'Repairing the Windows image — this can take 15–30 minutes…', desc: 'Fixes the source SFC repairs from. Run it before SFC if SFC fails.', long: { what: 'Runs "DISM /Online /Cleanup-Image /RestoreHealth".', why: 'Downloads clean copies of damaged system components from Windows Update.', risk: 'Safe. Needs internet; takes 15–30 minutes.' }, win: { kind: 'dism' } }),
  A({ id: 'act-remove-bloat', name: 'Remove preinstalled apps', category: 'cleanup', os: ['win32'], risk: 'moderate', params: 'bloat', confirm: 'The apps you tick are uninstalled for your account. Revert can\'t bring them back, but you can reinstall any of them free from the Microsoft Store.', desc: 'Uninstall preinstalled Microsoft apps you don\'t use.', long: { what: 'Removes the apps you choose for your user account.', why: 'Fewer background updates and notifications.', risk: 'Reinstall from the Microsoft Store if you change your mind.' }, choices: BLOAT.map(([id, label]) => ({ id, label })), win: (ctx, params) => ({ kind: 'removeAppx', names: (params.names || []).filter((n) => BLOAT.some(([id]) => id === n)) }) }),
  A({ id: 'act-standby-clear', name: 'Clear standby memory', category: 'cleanup', os: ['win32'], admin: true, desc: 'Frees RAM Windows is holding as cache — helps 8 GB PCs before a big game.', long: { what: 'Purges the standby memory list (the same thing ISLC/RAMMap do).', why: 'On low-RAM PCs a full standby list can cause stutter when a game needs memory quickly.', risk: 'Safe. Windows refills the cache over time; it\'s only worth doing on 8–16 GB PCs.' }, win: { kind: 'purgeStandby' } }),
  A({ id: 'act-purge-ram', name: 'Free cached memory', category: 'cleanup', os: ['darwin', 'linux'], admin: true, desc: 'Drops file caches from RAM before launching a big game.', long: { what: 'macOS: runs "purge". Linux: syncs and drops page caches.', why: 'Honest note: only useful on low-RAM machines right before a heavy game; the OS would free it anyway.', risk: 'Safe. Things load from disk once more afterwards.' }, sh: process.platform === 'darwin' ? 'purge' : 'sync; echo 3 > /proc/sys/vm/drop_caches' }),
  A({ id: 'act-cros-clear-cache', name: 'Clear Linux container cache', category: 'cleanup', os: ['chromeos'], desc: 'Frees space inside your Chromebook\'s Linux container.', long: { what: 'Deletes files older than a day in ~/.cache.', why: 'The Linux container has limited disk space.', risk: 'Safe.' }, sh: shClear(['"$HOME/.cache"'], 1440) }),
];
module.exports.BLOAT = BLOAT;
